name: so_pysm_models

channels:
    - astropy
    - conda-forge

dependencies:
    - python>=3.6
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - healpy
#   - pip:
#       - dependency_from_pip
